# Survival

```{r, echo=FALSE,warning=FALSE,message=FALSE,include=FALSE}
library(survival)
library(survminer)
library(tidyverse)
library(caret)
library(hrbrthemes)
library(viridis)
```

## Loading Data
```{r}
data(rotterdam)
```

```{r, echo=FALSE,warning=FALSE,message=FALSE,include=FALSE}
rotterdam <- rotterdam %>%
  mutate(Treatment = ifelse(chemo == 1 & hormon == 0, "Chemo", ifelse(chemo == 0 & hormon == 1, "Hormon", ifelse(chemo == 1 & hormon == 1, "Both", "NaN/Other Treatment"))))
rotterdam <- rotterdam %>% 
  mutate(Nodes_level = ifelse(nodes == 0, "N0", 
                              ifelse(nodes >= 1 & nodes <= 3, "N1", 
                                     ifelse(nodes >= 4 & nodes <= 9, "N2", 
                                            ifelse(nodes >= 10, "N3", NaN)))))
rotterdam <- rotterdam %>%
  mutate(grade = as.factor(grade))
```

## Kaplan-Miere

### `size` vs. Survival Times

`size` vs. `dtime`
```{r}
KM_None_Death <- survfit(Surv(dtime, death) ~ size, data = rotterdam)
plot(KM_None_Death, conf.type = "plain", col = c("black","red","blue"), xlab="Days", ylab="Survival")
legend(6000, 1, legend=c("<=20", "20-50", ">50"),
       col=c("black", "red", "blue"), lty=1, cex=0.8,
       title="Tumor Size", text.font=6)
```

`size` vs. `rtime`
```{r}
KM_None_Recur <- survfit(Surv(rtime, recur) ~ size, data = rotterdam)
plot(KM_None_Recur, conf.type = "plain", col = c("black","red","blue"), xlab="Days", ylab="Survival")
legend(6000, 1, legend=c("<=20", "20-50", ">50"),
       col=c("blue", "red", "blue"), lty=1, cex=0.8,
       title="Tumor Size", text.font=6)
```

### `Nodes_level` vs. Survival Times

`Nodes_level` vs. `dtime`
```{r}
KM_None_Death <- survfit(Surv(dtime, death) ~ Nodes_level, data = rotterdam)
plot(KM_None_Death, conf.type = "plain", col = c("black","red","blue","orange"), xlab="Days", ylab="Survival")
legend(5000, 1, legend=c("Both", "Chemo","Hormon", "NaN/Other Treatment"),
       col=c("black", "red", "blue", "orange"), lty=1, cex=0.8,
       title="Treatment Group", text.font=6)
```

`Nodes_level` vs. `rtime`
```{r}
KM_None_Recur <- survfit(Surv(rtime, recur) ~ Nodes_level, data = rotterdam)
plot(KM_None_Recur, conf.type = "plain", col = c("black","red","blue","orange"), xlab="Days", ylab="Survival")
legend(5000, 1, legend=c("Both", "Chemo","Hormon", "NaN/Other Treatment"),
       col=c("black", "red", "blue", "orange"), lty=1, cex=0.8,
       title="Treatment Group", text.font=6)
```

### `Treatment` vs. Survival Times

`Treatment` vs. `dtime`
```{r warning=FALSE}
KM_Treatment_Death <- survfit(Surv(dtime, death) ~ Treatment, data = rotterdam)
plot(KM_Treatment_Death, conf.int = FALSE, col = c("black", "red", "blue", "orange"), xlab="Days", ylab="Survival")
legend(1, 0.4, legend=c("Both", "Chemo","Hormon", "NaN/Other Treatment"),
       col=c("black", "red", "blue", "orange"), lty=1, cex=0.8,
       title="Treatment Group", text.font=6)
```

`Treatment` vs. `rtime`
```{r}
KM_Treatment_Recur <- survfit(Surv(rtime, recur) ~ Treatment, data = rotterdam)
plot(KM_Treatment_Recur, conf.int = FALSE, col = c("black", "red", "blue", "orange"), xlab="Days", ylab="Survival")
legend(1, 0.4, legend=c("Both", "Chemo","Hormon", "NaN/Other Treatment"),
       col=c("black", "red", "blue", "orange"), lty=1, cex=0.8,
       title="Treatment Group", text.font=6)
```

## Parametric Models

Log-normal model:
```{r}
Dlnorm <- survreg(Surv(dtime, death) ~ Treatment + size + nodes + age , dist='lognormal', data=rotterdam)
Dlnorm
CS <- -log(1 - plnorm(rotterdam$dtime, 9.709442268-0.431016329*(rotterdam$Treatment=="Chemo")
                                                  -0.346351742*(rotterdam$Treatment=="Hormon")  
                                                  -0.423626557*(rotterdam$Treatment=="NaN/Other Treatment")
                                                  -0.372703559*(rotterdam$size=="20-50")
                                                  -0.654189313*(rotterdam$size==">50")
                                                  -0.079103425*rotterdam$nodes 
                                                  -0.009903862*rotterdam$age, 
                                       1.077329))
# Make appropriate graph using CoxSnell function
CoxSnell(CS, rotterdam$death)
```

```{r}
Dlnorm <- survreg(Surv(rtime, recur) ~ Treatment + size + nodes + age, dist='lognormal', data=rotterdam)
Dlnorm
CS_r <- -log(1 - plnorm(rotterdam$rtime, 8.514204484-0.382172447*(rotterdam$Treatment=="Chemo")
                                                  -0.479063703*(rotterdam$Treatment=="Hormon")   
                                                  -0.605193863*(rotterdam$Treatment=="NaN/Other Treatment")
                                                  -0.458345796*(rotterdam$size=="20-50")
                                                  -0.738657689*(rotterdam$size==">50")
                                                  -0.107708963*rotterdam$nodes 
                                                  +0.009059467*rotterdam$age, 1.340545))
summary(Dlnorm)

# Make appropriate graph using CoxSnell function
CoxSnell(CS_r, rotterdam$recur)
```






## Cox-PH model:

```{r}
m_death = coxph(Surv(dtime, death) ~ Treatment + size + nodes + strata(age), data=rotterdam)
m_death
```

```{r}
cox.zph(m_death)
```


```{r}
m_recur = coxph(Surv(rtime, recur) ~ size, data=rotterdam)
m_recur
```

```{r}
cox.zph(m_recur)
```











